# Change these first
owner: crs-digital # Your GitHub organization or username, where this repository lives
repo: website-monitoring # The name of this repository
user-agent: crs-digital

sites:
  - name: CRS
    url: https://www.crs.org
  - name: CRS Español
    url: https://www.crsespanol.org
  - name: Support CRS
    url: https://support.crs.org
  - name: CRS Rice Bowl
    url: https://www.crsricebowl.org
  - name: Annual Report
    url: https://annualreport.crs.org
  - name: Changing the Way We Care
    url: https://www.changingthewaywecare.org
  - name: Coffeelands
    url: https://coffeelands.crs.org
  - name: Compass
    url: https://compass.crs.org
  - name: CRS Materials
    url: https://crsmaterials.crs.org
  - name: Farmer to Farmer
    url: https://farmertofarmer.crs.org
  - name: Gift Catalog
    url: https://gifts.crs.org
  - name: ICS
    url: https://ics.crs.org
  - name: ICT4D Conference
    url: https://www.ict4dconference.org
  - name: Impact / 75th Anniversary
    url: https://impact.crs.org
  - name: Onboarding
    url: https://onboarding.crs.org
  - name: OVC Support
    url: https://ovcsupport.org
  - name: Vatican Conference
    url: https://www.viiconference.org
  - name: Virtual Votive
    url: https://prayers.crs.org
  - name: SofTrek API
    url: https://webapps.softrek.com/crsprod/api/proc
    expectedStatusCodes:
      - 200

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /website-monitoring
  logoUrl: https://www.crs.org/sites/all/themes/crs/images/logo-crs-legacy.svg
  faviconSvg: https://raw.githubusercontent.com/crs-digital/website-monitoring/f0d42fde42e61a747a6fa42326bf3fd8ffd1afb7/assets/favicon.svg
  robotsText: "User-agent: * \n Disallow: /"
  customHeadHtml: "<link rel='stylesheet' type='text/css' href='https://cloud.typography.com/7240754/770086/css/fonts.css' /><style> body { font-family: font-family: 'Gotham A', 'Gotham B', Arial, Helvetica, sans-serif; } </style>"
  name: CRS Website Monitoring
  introTitle: "CRS website uptime monitoring."
  introMessage: Check here to verify whether a website is up or down.
  navbar:
    - title: Status
      href: /website-monitoring
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: light
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
